/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TheBookStore;

import DAO.EmployeeDAO;
import EntityClass.Employees;
import ExtentionLibrary.Auth;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import raven.alerts.MessageAlerts;
import raven.popup.GlassPanePopup;
import raven.toast.Notifications;

/**
 *
 * @author huynh
 */
public class Login extends javax.swing.JFrame {

    EmployeeDAO empDAO = new EmployeeDAO();

    public Login() {
        initComponents();
        GlassPanePopup.install(this);
        Notifications.getInstance().setJFrame(this);
        ImageIcon icon = new ImageIcon("src\\img\\Rimberio.png");
        setIconImage(icon.getImage());
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        lblHidePass = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtUsernameLogin = new javax.swing.JTextField();
        lblForgotPassLogin = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtPasswordLogin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHidePass.setBackground(new java.awt.Color(255, 255, 255));
        lblHidePass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHidePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hide.png"))); // NOI18N
        lblHidePass.setBorder(new javax.swing.border.MatteBorder(null));
        lblHidePass.setOpaque(true);
        lblHidePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHidePassMouseClicked(evt);
            }
        });
        pnlLogin.add(lblHidePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 60, 60));

        lblLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLogin.setText("ĐĂNG NHẬP");
        pnlLogin.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 26, -1, 27));

        txtUsernameLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsernameLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tên Đăng Nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtUsernameLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameLoginKeyPressed(evt);
            }
        });
        pnlLogin.add(txtUsernameLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 96, 341, 65));

        lblForgotPassLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblForgotPassLogin.setText("Quên mật khẩu?");
        lblForgotPassLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotPassLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblForgotPassLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblForgotPassLoginMouseExited(evt);
            }
        });
        pnlLogin.add(lblForgotPassLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 262, 130, 24));

        btnLogin.setBackground(new java.awt.Color(0, 204, 51));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profile.png"))); // NOI18N
        btnLogin.setText("ĐĂNG NHẬP");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 300, 160, 50));

        txtPasswordLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPasswordLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mật Khẩu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtPasswordLogin.setEchoChar('*');
        txtPasswordLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordLoginKeyPressed(evt);
            }
        });
        pnlLogin.add(txtPasswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 179, 290, 65));

        getContentPane().add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 524, 386));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public boolean checkLogin() {
        String userName = txtUsernameLogin.getText();
        String passWord = new String(txtPasswordLogin.getPassword());
        if (userName.isEmpty()) {
            MessageAlerts.getInstance().showMessage("The BookStore", "Vui lòng nhập tên đăng nhập!", MessageAlerts.MessageType.ERROR);
            return true;
        }
        if (passWord.isEmpty()) {
            MessageAlerts.getInstance().showMessage("The BookStore", "Vui lòng nhập mật khẩu!", MessageAlerts.MessageType.ERROR);
            return true;
        }
        List<Employees> e = empDAO.selectByName(userName);
        if (e == null) {
            MessageAlerts.getInstance().showMessage("The BookStore", "Tài khoản không tồn tại!", MessageAlerts.MessageType.ERROR);
            return true;
        }
        if (!passWord.equals(e.get(0).getEmployeePassword())) {
            MessageAlerts.getInstance().showMessage("The BookStore", "Sai mật khẩu!", MessageAlerts.MessageType.ERROR);
            return true;
        }
        return false;
    }

    void init() {
        ImageIcon labelIcon = new ImageIcon("src//img//hide.png");
        lblHidePass.setIcon(labelIcon);
    }

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (!checkLogin()) {
            List<Employees> e = empDAO.selectByName(txtUsernameLogin.getText());
            Auth.user = e.get(0);
            try {
                new TheBookStoreJFrame().setVisible(true);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblForgotPassLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPassLoginMouseEntered
        lblForgotPassLogin.setText("<html><u>Quên mật khẩu ?</u></html>");
        lblForgotPassLogin.setForeground(Color.red);
    }//GEN-LAST:event_lblForgotPassLoginMouseEntered

    private void lblForgotPassLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPassLoginMouseExited
        lblForgotPassLogin.setText("Quên mật khẩu?");
        lblForgotPassLogin.setForeground(Color.black);
    }//GEN-LAST:event_lblForgotPassLoginMouseExited

    private void lblForgotPassLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPassLoginMouseClicked
        new ForgetPassword().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblForgotPassLoginMouseClicked

    private void lblHidePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHidePassMouseClicked
        if (txtPasswordLogin.getEchoChar() != 0) {
            txtPasswordLogin.setEchoChar((char) 0); // Hiện mật khẩu
            ImageIcon icon = new ImageIcon("src//img//view.png");
            lblHidePass.setIcon(icon);
        } else {
            txtPasswordLogin.setEchoChar('*'); // Ẩn mật khẩu
            ImageIcon icon = new ImageIcon("src//img//hide.png");
            lblHidePass.setIcon(icon);
        }
    }//GEN-LAST:event_lblHidePassMouseClicked

    private void txtPasswordLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordLoginKeyPressed
        this.pressEnter(evt);
    }//GEN-LAST:event_txtPasswordLoginKeyPressed

    private void txtUsernameLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameLoginKeyPressed
        this.pressEnter(evt);
    }//GEN-LAST:event_txtUsernameLoginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblForgotPassLogin;
    private javax.swing.JLabel lblHidePass;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPasswordField txtPasswordLogin;
    private javax.swing.JTextField txtUsernameLogin;
    // End of variables declaration//GEN-END:variables
    
    private void pressEnter(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLogin.doClick();
        }
    }
}
