/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package TheBookStore;

import DAO.ReceiptsDAO;
import EntityClass.Receipts;
import ExtentionLibrary.XDate;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.Currency;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ViewReceipts extends javax.swing.JDialog {

    /**
     * Creates new form ViewReceipts
     */
    public ViewReceipts(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        vndFormatter.setCurrency(vnd);
        init();
    }
    
    Locale locale = new Locale("vi", "VN");
    Currency vnd = Currency.getInstance("VND");
    NumberFormat vndFormatter = NumberFormat.getCurrencyInstance(locale);
    
    public String reID = "";
    public String status = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReceipts = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DANH SÁCH HÓA ĐƠN");

        tblReceipts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblReceipts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblReceipts.setRowHeight(25);
        tblReceipts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReceiptsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReceipts);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH HÓA ĐƠN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblReceiptsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReceiptsMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2)
        {
            int row = tblReceipts.getSelectedRow();
            String id = tblReceipts.getValueAt(row, 0).toString();
            try {
                Receipts receipt = dao.selectById(id);
                this.reID = receipt.getID();
                this.status = receipt.getCurrentStatus();
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(ViewReceipts.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tblReceiptsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReceipts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReceipts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReceipts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReceipts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewReceipts dialog = null;
                try {
                    dialog = new ViewReceipts(new javax.swing.JFrame(), true);
                } catch (SQLException ex) {
                    Logger.getLogger(ViewReceipts.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    void init() throws SQLException
    {
        fillReceipts();
        tblReceipts.setDefaultEditor(Object.class, null);
    }
    
    ReceiptsDAO dao = new ReceiptsDAO();
    Comparator<Receipts> com = new Comparator<Receipts>() {
            @Override
            public int compare(Receipts o1, Receipts o2) {
                String date1 = o1.getID().substring(2, 11);
                String date2 = o2.getID().substring(2, 11);
                
                date1 = date1.substring(0, 2) + "-" + date1.substring(2, 4) + "-" + date1.substring(4);
                date2 = date2.substring(0, 2) + "-" + date2.substring(2, 4) + "-" + date2.substring(4);
                
                int returnValue = XDate.toDate(date1, "dd-MM-yyyy").compareTo(XDate.toDate(date2, "dd-MM-yyyy"));
                
                if (returnValue != 0)
                {
                    return returnValue;
                }
                else
                {
                    String index1 = o1.getID().substring(11);
                    String index2 = o2.getID().substring(11);
                    
                    return index1.compareTo(index2);
                }
            }

            @Override
            public Comparator<Receipts> reversed() {
                return Comparator.super.reversed();
            }
            
        };
    
    void fillReceipts() throws SQLException
    {
        String[] header = new String[] {"MÃ HÓA ĐƠN", "TỔNG TIỀN", "TRẠNG THÁI", "NGÀY TẠO"};
        DefaultTableModel model = new DefaultTableModel(header,0);
        List<Receipts> list = dao.selectAll();
        Collections.sort(list, com.reversed());
        for (Receipts r : list)
        {
            Object[] row = new Object[]{r.getID(), vndFormatter.format(r.getTotalCost()), r.getCurrentStatus(), r.getCreateDate() };
            model.addRow(row);
        }
        tblReceipts.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReceipts;
    // End of variables declaration//GEN-END:variables
}
